### ISSUE TITLE
Export `TEMPORAL_ADDRESS` of current cluster in admintools

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#455]
It would be nice to export `TEMPORAL_ADDRESS` of the current cluster in admintools.

Currently, it shows an error on default address.
```
temporal-tok-admintools-dc4d868f7-xd2cp:/etc/temporal$ temporal operator cluster describe
Error: unable to get cluster information: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:7233: connect: connection refused"
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```

**Comment by alexandrevilain** [comment]
Hi @yujunz ! 
Looks likes it's due to the new temporal cli, `tctl` requires `TEMPORAL_CLI_ADDRESS` which is exposed in the container: https://github.com/alexandrevilain/temporal-operator/blob/main/internal/resource/admintools/deployment_builder.go#L84.

It could be really easy to add it, i'll fix it soon :)
