### ISSUE TITLE
temporal namespace not created when temporal cluster is recreated

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#475]
Steps to reproduce
1. Create temporal cluster
2. Create temporal namespace
3. Delete temporal cluster
4. Recreate temporal cluster

Expected
* temporal namespace recreated

Actual
* temporal namespace not created

Not sure if it is a bug or expected behavior.

**Comment by alexandrevilain** [comment]
Hi @yujunz !
Thanks for this issue! 

The fix should be pretty easy, the TemporalNamespace controller should watch for TemporalClusters and enqueue TemporalNamespace reconciliations when referenced TemporalClusters are updated. 

I’ll try to fix this asap.

**Comment by yujunz** [comment]
Maybe it is expected behavior since the cluster might be a different one that happens to have the same name.

IMHO, cluster controller should block deletion if it is still referenced.

And the cluster ref in namespace might be better to resolve to unique id of the cluster not a weak link by name.

What do you think?

**Comment by alexandrevilain** [comment]
> Maybe it is expected behavior since the cluster might be a different one that happens to have the same name and it is intended to not claim existing namespaces. 
> IMHO, cluster controller should block cluster deletion if it is still referenced by any namespace or cascading delete all namespaces or orphan them, depends on some options configured.

Yes you're right. I'll try to develop this kind of behavior. When a Cluster is deleted all its dependent objects are deleted too: namespace, clusterclient, workerprocess.

> And the cluster ref in namespace might be better to resolve to unique id of the cluster not a weak link by name.

This is really common in Kubernetes to reference things by name. In a GitOps environment it would be really harder to reference by ID because resources are applied at the same time. 

Thanks for this issue it helped me see that namespaces where not updated when clusters are updated, this is now fixed by #481. Then we have to think about cascade delete.
