### ISSUE TITLE
Support generic sidecar for both services and database creation/update jobs

### ISSUE THREAD

**Issue by alexandrevilain** [alexandrevilain/temporal-operator#600]
### Discussed in https://github.com/alexandrevilain/temporal-operator/discussions/599

<div type='discussions-op-text'>

<sup>Originally posted by **djMax** January  3, 2024</sup>
We are running in GCP (GKE) using a CloudSQL postgres instance. I have added the cloudsql sidecare to the deployment overrides, but it seems like the operator spins up a bunch of jobs first, and those jobs do not inherit the sidecar options. Is it possible to use the operator to deploy in a GCP CloudSQL environment?</div>

**Comment by djMax** [comment]
So I did get this working in the temporal helm chart and here are my notes if they are helpful. The sidecar is pretty straightforward, BUT:

1) Most use cases will want the jobs/pods to run with a specific serviceAccount so that the proxy can handle auth
2) Most use cases will not require a password for the db (since it's localhost) and so it's a waste to create secrets for fake passwords (so this should allow some dummy password)
3) All services need to wait for the proxy to be ready. I had to modify the temporal docker container commands to versions of this:

```
          command: ["/bin/sh", "-c"]
          args:
            - |
              until nc -z localhost 5432; do
                echo "Waiting for PostgreSQL to be available on port 5432..."
                sleep 1
              done
              sleep 1
              echo "PostgreSQL is up and running on port 5432!"
              temporal-sql-tool setup-schema -v 0.0
```

or 

```
          command: ["/bin/sh", "-c"]
          args: ["sleep 5; /etc/temporal/entrypoint.sh autosetup"]
```

**Comment by alexandrevilain** [comment]
Thanks for the valuable insights. 
Are you interested on contributing to add this feature on the operator ?

**Comment by djMax** [comment]
If I can help I certainly will, but I will say operators have always confused me and this one is big enough to be no exception. But if you point me I can chase.

**Comment by alexandrevilain** [comment]
@djMax for sure I can help you with your first contribution on an operator :)

**Comment by alexandrevilain** [comment]
Closing as sidecars are now available in the API.
