### ISSUE TITLE
Have Operator Deploy dashboards as ConfigMaps

### ISSUE THREAD

**Issue by ElanHasson** [alexandrevilain/temporal-operator#630]
It'd be really cool to have the operator optionally deploy the latest grafana dashboards from https://github.com/temporalio/dashboards to a namespace for getting picked up by grafana.

https://github.com/alexandrevilain/temporal-operator/blob/1b5d2bfc9bce9715657391762719425015a466e7/docs/features/monitoring/prometheus-operator.md?plain=1#L39

**Comment by alexandrevilain** [comment]
Hi @ElanHasson !

Thanks for the proposal. This is definitely something an operator should do. 
But the last time I checked for the dashboard they were not importable "as-is" in any grafana due to hardcoded datasources and other things like that... 

Maybe it has been updated. If it's not the case I'll not do this because I don't want to get issues about graphs we don't maintain in this repository. I hope you understand ;)
